version: '3.4'

services:
  webapplication:
    image: ${DOCKER_REGISTRY-}webapplication
    env_file: docker.private.env
    restart: always
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
